CREATE DATABASE IF NOT EXISTS friendsdb WITH OWNER postgres;
\c friendsdb

CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  phoneNumber VARCHAR(255) NOT NULL,
  notes TEXT,
  userId VARCHAR(255) UNIQUE NOT NULL,
);